# docker-compose.production.yml
volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    container_name: kitty_db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: katomy/kitty_backend # Качаем с Docker Hub
    container_name: kitty_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static
      - media:/app/media

  frontend:
    image: katomy/kitty_frontend  # Качаем с Docker Hub
    container_name: kitty_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: katomy/kitty_gateway  # Качаем с Docker Hub
    container_name: kitty_gateway
    env_file: .env
    volumes:
      - static:/static
      - media:/app/media
    ports:
      - 9000:80
